# Generated by Django 6.1 on 2026-09-05 22:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complexity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Planned duration in calendar days.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
