# Generated by Django 6.1 on 2026-09-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_chat_message_conversation_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('PRIVATE', 'Private conversation')], default='PRIVATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('ATTACHMENT', 'Attachment')], default='TEXT', max_length=20),
        ),
    ]
