# Generated by Django 6.1 on 2026-09-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5),
        ),
    ]
