# Generated by Django 6.1 on 2026-09-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_langue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('REGISTER', 'Registration verification'), ('PASSWORD_RESET', 'Password reset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='langue',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Administrator')], default='MEMBER', max_length=15),
        ),
    ]
