# Generated by Django 6.1 on 2026-09-28 23:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailotp_purpose_alter_user_langue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.profile_photo_upload_path, validators=[accounts.models.validate_profile_photo], verbose_name='Profile photo'),
        ),
    ]
