# Generated by Django 6.1 on 2026-09-06 05:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('NOT_DONE', 'Not done'), ('DONE', 'Done')], default='NOT_DONE', max_length=10)),
                ('position', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
            ],
            options={
                'ordering': ['position', 'created_at', 'pk'],
                'indexes': [models.Index(fields=['task', 'position'], name='task_subtask_position_idx'), models.Index(fields=['task', 'status'], name='task_subtask_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'position'), name='unique_subtask_position_per_task')],
            },
        ),
    ]
