# Generated by Django 6.1 on 2026-09-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('NOT_DONE', 'Non terminée'), ('DONE', 'Terminée')], default='NOT_DONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminée')], default='TODO', max_length=20),
        ),
    ]
