# Generated by Django 6.1 on 2026-09-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_subtask_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('NOT_DONE', 'Not completed'), ('DONE', 'Completed')], default='NOT_DONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Completed')], default='TODO', max_length=20),
        ),
    ]
